### ISSUE TITLE
Support switching between v6 and v7 docs

### ISSUE THREAD

**Issue by existentialism** [babel/website#1261]
@raspo has stepped up to help! :)

**Comment by xtuc** [comment]
What about a subdomain? Seperate website?

https://github.com/babel/babel.github.io/pull/1187 must ne done first.

**Comment by Daniel15** [comment]
For what it's worth, now that we're on Netlify, they have the concept of branch subdomains. You can create a subdomain like `7.babeljs.io` which would be served from the `7` branch instead of the `master` branch. https://www.netlify.com/docs/custom-domains/#branch-subdomains

The other option is to have all the content on a single site and handle it that way, but it might be trickier.

**Comment by xtuc** [comment]
Yes @Daniel15 that would be awesome.

We have currently the 6.0, 7.0 and 5.0 branch that could have the documentation online.

**Comment by hzoo** [comment]
Will by done by https://github.com/babel/website/pull/1521
