### ISSUE TITLE
Should the REPL debounce changes?

### ISSUE THREAD

**Issue by Daniel15** [babel/website#1316]
The current REPL debounces changes and only runs the transformation after 500ms. The new one transforms the file immediately. I imagine the debouncing is useful when you're working with very large code blocks.

The new REPL should debounce all text inputs, including:
* The main code input
* Env preset textarea
* Env preset Node and Electronic number inputs

Note that this will be a little more involved than is ideal due to the way the `compile` function is currently (synchronously) hooked into `Repl.setState`. Debouncing input has a negative impact on controlled input components, so we'll need to refactor `Repl` to separate the compiled output (code, source maps, errors, etc) from the controlled inputs.

**Comment by bvaughn** [comment]
At best, only textarea/text changes shoupd be debounecd

On Aug 14, 2017 8:38 PM, "Daniel Lo Nigro" <notifications@github.com> wrote:

The current REPL debounces changes and only runs the transformation after
500ms. The new one transforms the file immediately. I imagine the
debouncing is useful when you're working with very large code blocks.

cc @bvaughn <https://github.com/bvaughn>, do you think this behaviour is
worth keeping?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/babel/website/issues/1316>, or mute the thread

**Comment by bvaughn** [comment]
I considered denouncing but decided against it. (It wasn't so much a strong decision as...I didn't want to keep scope creeping the original PR.)

That being said, I think it's reasonable to debounce the `<textarea>`/`<input type="number">` for the env preset but nothing else. (Checkboxes don't need to be debounced. It's not really useful and it's not worth the added complexity.)

**Edit** Sorry for the sloppy initial reply. Was on mobile.

**Comment by xtuc** [comment]
https://github.com/babel/website/pull/880 is bit old but very interesting. What do you think about that?

**Comment by bvaughn** [comment]
I've also been bouncing around that idea.

**Comment by bvaughn** [comment]
Whoops. We should also debounce the main REPL text input 🤡
