### ISSUE TITLE
New REPL doesn't include regenerator runtime

### ISSUE THREAD

**Issue by fnky** [babel/website#1350]
While the new REPL does include [`transform-regenerator`](https://github.com/babel/website/blob/master/js/repl/compile.js#L76), it doesn't use the regenerator runtime to be able to run async functions and generators:

```js
(async () => {})()
```

outputs the following:

```js
"use strict";

function _asyncToGenerator(fn) { return function () { var gen = fn.apply(this, arguments); return new Promise(function (resolve, reject) { function step(key, arg) { try { var info = gen[key](arg); var value = info.value; } catch (error) { reject(error); return; } if (info.done) { resolve(value); } else { return Promise.resolve(value).then(function (value) { step("next", value); }, function (err) { step("throw", err); }); } } return step("next"); }); }; }

_asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
  return regeneratorRuntime.wrap(function _callee$(_context) {
    while (1) {
      switch (_context.prev = _context.next) {
        case 0:
        case "end":
          return _context.stop();
      }
    }
  }, _callee, undefined);
}))();
```

which throws:

```
regeneratorRuntime is not defined
```

This works fine in the old REPL.

**Comment by hzoo** [comment]
maybe we aren't including babel-polyfill anymore, didn't check

**Comment by bvaughn** [comment]
We lazy-load `babel-polyfill` (which includes the regenerator runtime) if you check "Evaluate"

**Comment by bvaughn** [comment]
Just confirmed that selecting the "Evaluate" option loads [bundle.run/babel-polyfill@6.26.0](https://bundle.run/babel-polyfill@6.26.0), and that bundle defines a top-level `regeneratorRuntime` function.

And we [load it on the UI thread](https://github.com/babel/website/blob/master/js/repl/Repl.js#L236-L239) which is where we evaluate things.

But I also see the warning you're mentioning on the right-hand side:
> regeneratorRuntime is not defined

Setting a breakpoint in the evaluated code, I'm able to confirm that there's no `regeneratorRuntime` method in scope.

Ah! I believe this broke when I moved evaluation into an `<iframe>`. The `contentWindow` doesn't inherit user-defined values like the polyfill. I'll need to copy them over before evaluating.

**Comment by bvaughn** [comment]
I think a better solution would be to just load the runtime polyfill directly into the iframe we're evaling in. I'll look into making this change soon. 😄

**Comment by Daniel15** [comment]
@bvaughn  - Could we update it to load babel-polyfill via unpkg (https://unpkg.com/babel-polyfill@6.26.0/dist/polyfill.min.js) rather than bundle.run? The resulting file is about 2 KB smaller.

**Comment by bvaughn** [comment]
Hm. I guess I could? Some things (eg Prettier) aren't loadable directly from unpkg which is why I was using bundle.run. At one point I was using both and switching between via an optional `PluginConfig` flag. We could do that again, sure. I'd say file it as a separate issue though since it's unrelated to this? 😄

**Comment by Daniel15** [comment]
> Some things (eg Prettier) aren't loadable directly from unpkg

We should get Prettier to fix that (or submit a PR to fix it) :P 

>  I'd say file it as a separate issue though since it's unrelated to this? 😄

Good idea!

**Comment by bvaughn** [comment]
> > Some things (eg Prettier) aren't loadable directly from unpkg

> We should get Prettier to fix that (or submit a PR to fix it) as it means that something is broken in the package. :P

File an issue with them then? 😄

It seemed intentional (to me) that they don't publish a UMD bundle to NPM. I assumed they didn't expect anyone to load it in the browser because it's so large and not a common use-case.

Looks like their [service worker](https://github.com/prettier/prettier/blob/gh-pages/service-worker.js) uses [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox) to load a [minified version of Prettier that's committed directly to their `gh-pages` branch](https://github.com/prettier/prettier/tree/gh-pages/lib).
