### ISSUE TITLE
Load polyfills from polyfill.io rather than babel-polyfill

### ISSUE THREAD

**Issue by Daniel15** [babel/website#1366]
`babel-polyfill` is very heavy, and the REPL loads it when you select the "evaluate" option. Let's instead use a conditional polyfilling service like `polyfill.io` that only loads the polyfills your browser actually needs. I'd say that most users of the REPL would be using a relatively modern browser, so this should reduce load time.

We'll need to be sure to load the regenerator runtime though.
```
import "regenerator-runtime/runtime";
```

**Comment by zloirock** [comment]
I'm strictly against of usage `polyfill.io` in the REPL because it contains very incorrect polyfills and only a little part of polyfilled features from `babel-polyfill`.

**Comment by bvaughn** [comment]
Seems like there's more consensus here _not_ to use polyfill.io than there is _to_ use it and I'm not aware of an alternative that's more reliable.

I agree that `babel-polyfill` is heavy, but we do JIT load it only if the user selects "Evaluate", so there's that.

I think for now it's okay to close this issue. Let's reopen it if we settle on a course of action that's less controversial. 😄

**Comment by Daniel15** [comment]
Okay, sounds reasonable. Thanks!

>  Let's reopen it if we settle on a course of action that's less controversial. 😄

I wonder if we could have a few babel-polyfill builds for the most common browser capabilities, and just load the right one based on capabilities. Even just two or three would be useful:

 - Very old browser (load everything)
 - Reasonably modern browser (don't polyfill promises,. `Map`, `Set`, etc.)

**Comment by xtuc** [comment]
Another solution would be to add babel-preset-env in bundle.run. We could pass the browser in query parameters. It will defeats a bit the purpose of the CDN since it will bypass it for each new browser.

**Comment by Daniel15** [comment]
> It will defeats a bit the purpose of the CDN since it will bypass it for each new browser.

Yeah, it's impossible have effective edge caching if the content varies by User-Agent, unless you encode that information into the filename. I think just having two builds ("old browsers" and "modern browsers") is probably sufficient initially.

**Comment by xtuc** [comment]
Ok, to be efficient we could pass either Chrome 50 or Chrome 30 (or something like that) depending on the browser version which we could get on the client-side in JavaScript.

**Comment by zloirock** [comment]
@thedamon by my opinion, `polyfill.io` is a good service with bad polyfills.

You can see `polyfill.io` position about the correctness of polyfills [here](https://github.com/Financial-Times/polyfill-service/issues/192#issuecomment-216044063). You can check the source code of polyfills from `polyfill.io` in their repo. Just an example - [leaking `WeakMap` polyfill](https://github.com/Financial-Times/polyfill-service/blob/master/packages/polyfill-library/polyfills/WeakMap/polyfill.js). They have some progress in the previous year, but because they regularly have issues like [this](https://github.com/Financial-Times/polyfill-service/issues/1403), I can't recommend it for usage. `polyfill.io` use polyfills from different authors/projects which doesn't well play together.

`core-js` / `babel-polyfill` includes much more features than `polyfill.io`. Just some example - `regenerator` runtime for generators / async functions, polyfills for ES proposals, typed arrays, the logic of almost all well-known symbols, etc.

105kb of `babel-polyfill` you will have only with full bundle, but it's modular. You can load only required part of `core-js`. You can automatize this process with [`preset-env` with `useBuiltIns` option](http://new.babeljs.io/docs/en/next/babel-preset-env.html#usebuiltins).

`polyfill.io` service approach definitely makes sense, it can by applied to `core-js` in the future, but now I haven't any time and motivation for working on it.

**Comment by thedamon** [comment]
This is an awesome explanation. Thank you!

I may look at polyfill.io for DOM API polyfills only, if they have a way to
limit it to only old browsers and then conditionally load subsets of
babel-polyfill in old browsers.

**Comment by caub** [comment]
I'm not sure polyfill.io has less features

- https://unpkg.com/babel-polyfill@6.26.0/dist/polyfill.min.js is 105kB
- https://cdn.polyfill.io/v3/polyfill.min.js?flags=always&features=all is 300kB

polyfill.io has Intl polyfill for example

**Comment by Daniel15** [comment]
> this has not aged well

lol, yeah. These days, I think the approach I mentioned in this comment is best:

> I think just having two builds ("old browsers" and "modern browsers") 

since modern browesrs need very few polyfills. Most of the popular web platform features are supported by the major browsers.

**Comment by anurag-ar** [comment]
Seecurity Vulnerability on using polyfill.io[https://thehackernews.com/2024/06/over-110000-websites-affected-by.html](url)
