### ISSUE TITLE
Minify doesn't work in the REPL anymore

### ISSUE THREAD

**Issue by xtuc** [babel/website#1405]
See [REPL](https://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=false&code_lz=IxA&debug=false&circleciRepo=&evaluate=true&lineWrap=true&presets=es2015%2Cstage-0%2Cbabili&targets=&version=7.0.0-beta.1)

The error is the following: `repl: traverse.clearCache is not a function`.

/cc @boopathi

**Comment by existentialism** [comment]
Probably because current minify isn't compatible with babel 7? Seems to [work fine with 6.x](https://babeljs.io/repl/#?babili=true&browsers=&build=&builtIns=true&code_lz=IxA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015%2Cstage-0%2Cbabili&targets=Node-4&version=6.26.0)

On another note, we likely need to tie a versions of preset-env and minify to the `version` flag passed in.

**Comment by xtuc** [comment]
Yes right @existentialism, there's the PR in WIP https://github.com/babel/minify/pull/487.

Could we maybe add an error when calling preset-env/minify with an unsupported Babel version? babel-core exports its version IRC.

**Comment by hzoo** [comment]
Fixed at some point
