### ISSUE TITLE
Why was lodash dropped on REPL?

### ISSUE THREAD

**Issue by markogresak** [babel/website#1423]
I often used Babel REPL to test a snippet of code using lodash. Why was it removed?
Among other issues (removed console pane, worse bracket and autocomplete, etc.), the lack of lodash is the most common problem I keep running into and it is causing me to use the REPL less and less. 
Would you consider adding lodash back? Or at least adding a checkbox in the side menu to include it on the page?

**Comment by xtuc** [comment]
While I agree that it would be useful to have lodash in the REPL, we don't want to support adding every package on npm.

**Comment by hzoo** [comment]
There is no reason other than that it was used before and I guess we didn't need it anymore? If you used the REPL to specifically test lodash I would use their docs instead or just include the script yourself since it's just a global script injection (similar to how people added jquery to a page).

https://github.com/babel/website/issues/858 is a separate ticket to be able to import any npm package which would eventually solve this. We aren't going to add pkgs that we aren't using

If you have issues with the new repl compared to the old code please make a new issues or submit a PR, we can't know all the ways people used the REPL before. Should probably remember we are a group of volunteers. (We should add the issue comment in this repo too)

**Comment by markogresak** [comment]
I was using code snippets from the existing project, which often use syntax that needs to be transpired in order to work in the browser. And editing the code in the REPL is easier than writing the code directly in the console. 
I'm now usually relying on codepen or the web maker chrome plugin as a replacement for babel REPL. But having an option to import any npm package would be really nice. 🙂

**Comment by bvaughn** [comment]
Sorry for the inconvenience!

One of the goals of the rewritten REPL was to be as fast and light weight as possible for users with slow connections. Pulling in all of lodash is not ideal from that perspective.

That being said, #858 should address this issue. I don't think any Lodash specific action needs to be taken.

**Comment by hzoo** [comment]
Ok closing
