### ISSUE TITLE
Unexpected ID / Token on imports

### ISSUE THREAD

**Issue by djsneaks123** [babel/website#1611]
I have a stack overflow link were on my project i am using babel, but for some odd reason it does not like my imports and complains, i think i might have a issue with babel not working correctly.

link: https://stackoverflow.com/questions/48994051/babel-loader-unable-to-handle-imports-give-syntaxerror-unexpected-id-token 

please delete this if this is not the correct for me to post this here.
Thanks,
David.

**Comment by loganfsmyth** [comment]
That doesn't appear to be a runtime error error but rather Chrome's debugger itself is trying to process the file for something and is getting an error while doing it. I don't know why they show the error to users to begin with, but I believe I heard that it has been fixed in Chrome Canary at least.

If your app isn't working, it is likely something unrelated to the error message in your screenshots.

**Comment by djsneaks123** [comment]
@loganfsmyth  You are wrong. It has nothing to do with chrome's debugger, it is not loading the javascript file (when i step into it acts as if there is no file to go to). The same thing happens in IE. There probubly is an issue with my code, but im not sure what is causing it.
