### ISSUE TITLE
Heading for 7.0 post is invalid

### ISSUE THREAD

**Issue by hzoo** [babel/website#1780]
https://babeljs.io/blog/2018/08/27/7.0.0 title heading links to https://babeljs.io/blog/2018/08/27/7?

@joelmarcey?

**Comment by JoelMarcey** [comment]
@hzoo Oh no - I am sure this how we are processing the id to get the url. Probably a regex not taking into account `.` or something. We may not have tested blog names with `.` in them.

cc: @yangshun, @endiliey

**Comment by yangshun** [comment]
Yes, that's possibly why. We'll file a task in Docusaurus.

**Comment by JoelMarcey** [comment]
@hzoo You published the blog with what should be the correct link. Did you just manually update it?

**Comment by hzoo** [comment]
Haha yeah I guess most people are just doing the version number as the url.

>  Did you just manually update it?

What do you mean by this?

**Comment by JoelMarcey** [comment]
@hzoo I think I was slightly confused. It is the blog title within the blog that screws up, not the actual link to the blog. I just saw that you published the blog post and given what I thought was the error, I thought you might have manually updated the link to the blog post to be `7.0.0` instead of `7`.

**Comment by hzoo** [comment]
oh sorry yeah I certainly could of been more clear, just had someone message me about it!

**Comment by endiliey** [comment]
Just saw this. I'll work on a fix

**Comment by hzoo** [comment]
Yep, Fixed by https://github.com/babel/website/pull/1824!
