### ISSUE TITLE
ENV preset is broken (?)

### ISSUE THREAD

**Issue by zerkms** [babel/website#1879]
I expect this following code

```js
const a = {};
const b = {...a, foo: 'bar'};
```

to work with all "hardcoded" presets unchecked and env preset enabled with `chrome >= 69` selector.

Yet it fails to emit code: repl: Unexpected token (2:11)

url: https://babeljs.io/repl#?babili=false&browsers=chrome%20%3E%3D%2069&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDA3gXwNwChSVgIyVQDpS4AaGAMxBAC4YByfOAJ0cyA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=true&targets=&version=6.26.0&envVersion=1.6.2

**Comment by vladshcherbin** [comment]
@zerkms you are using old version of repl, use this link instead - https://babeljs.io/repl/build/master.

Related to https://github.com/babel/website/issues/1793

**Comment by zerkms** [comment]
I see, is there a way to switch to `build/master` from the UI?

**Comment by vladshcherbin** [comment]
> I see, is there a way to switch to `build/master` from the UI?

Don't think so.

I also think repl is outdated, here is [env plugin used](https://github.com/babel/website/blob/master/js/repl/PluginConfig.js#L23) and [package.json env version](https://github.com/babel/website/blob/master/package.json#L45). Will be probably fixed with this babel 7 pr - https://github.com/babel/website/pull/1483, until then repl is kinda broken/misleading with fake link versions.

**Comment by zerkms** [comment]
Yep, thanks for the references!
