### ISSUE TITLE
null coalescing

### ISSUE THREAD

**Issue by t0lkman** [babel/website#2095]
When I use babel.js online editor (try mode) I had to turn on stage-0 to support `null coalescing` while the proposal states it's already on stage-3 https://github.com/tc39/proposal-nullish-coalescing

is the website not updated yet or the feature in reality in stage-0?

**Comment by JLHwung** [comment]
As of Babel 7, all the `babel-preset-stage-*` is deprecated, you can add `proposal-null-coalescing-operator` in [REPL](https://babeljs.io/repl#?babili=false&browsers=safari%2011&build=&builtIns=usage&spec=true&loose=false&code_lz=IYAg_GIEZA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=7.6.4&externalPlugins=%40babel%2Fplugin-proposal-nullish-coalescing-operator%407.4.4).

**Comment by nicolo-ribaudo** [comment]
We still maintain the stage presets in `@babel/standalone`, because they are easier to use in the REPL.
@t0lkman Do you want to open a PR to move this plugin (and the optional chaining one) from https://github.com/babel/babel/blob/4f0840ab88037fb0241a745f7e4b0f8969709ef3/packages/babel-standalone/src/preset-stage-1.js to the stage 3 file?
