### ISSUE TITLE
Change the shorthands from babel-plugin-… to @babel/plugin-…

### ISSUE THREAD

**Issue by dilyanpalauzov** [babel/website#2244]
https://babeljs.io/docs/en/plugins#plugin-shorthand says:
> If the name of the package is prefixed with babel-plugin-, you can use a shorthand: … (skip this prefix)

https://babeljs.io/docs/en/presets#preset-shorthand says:
> If the name of the package is prefixed with babel-preset-, you can use a shorthand: (skip this prefix)

As plugins and presets are commonly not prefixed with `babel-plugin-` or `babel-preset-`, but with `@babel/plugin-` and `@babel/preset-` change the shorthand options to `@babel/preset-` and `@babel/plugin-`.

**Comment by JLHwung** [comment]
I think we can list both `@babel/plugin` and `babel-plugin` as supported prefixes because
1) `@babel/core` supports both of them
2) Conventionally community plugins that are not hosted in `babel` repo start with `babel-plugin-`: e.g. `babel-plugin-istanbul`, `babel-plugin-dynamic-import-node` and a few others to name.

**Comment by dilyanpalauzov** [comment]
> @babel/core supports both of them

I am not sure what this means concerning the current state.

Calling `babel-cli --preset='typescript'` does not work (cannot find module 'babel-preset-typescript'), while `babel-cli --preset='@babel/preset-typescript` does work.

**Comment by hzoo** [comment]
Not sure if behavior changed but testing `babel-cli --presets='typescript'` (preset should be presets) will give the error

> Did you mean "@babel/typescript"?

which is expected since you need the org `@babel` part assuming `@babel/preset-typescript` was installed

But the example may be confusing if you are using Babel's presets vs one on npm so we can change that
